First stage of implementation
Byndyusoft/byndyusoft-architecture-testing pull request #1
Opened 2024-06-29 08:06 UTC by litichevskiydv

2024-07-31 13:56 UTC, Mblkolo requested changes

2024-07-31 13:56 UTC, Mblkolo commented on README.md
> +- add the architecture package and the `Byndyusoft.ArchitectureTesting.StructurizrParser` package to the project;
> the architecture package

что за пакет? из описания не понятно

2024-07-31 13:56 UTC, Mblkolo commented on examples/Api.Tests/musicality-labs.dsl
> +		container storage {
Форматирование?

2024-07-31 13:56 UTC, Mblkolo commented on README.md
> +## Usage
Описалово слабое. Я совсем не понял как работает процесс в целом и почему я должен писать свой валидатор.
Новичкам будет сложно.
Непонятно что писать в валидаторе, непонятно что писать в тесте.

В общем не хватает идеи за счёт чего происиходит тестирование архитектуры.
Типа "сравниваем описание архитектуры с .....", а вот с чем сравниваем непонятно.

2024-07-31 13:56 UTC, Mblkolo commented on src/Abstractions/ServiceImplementations/ServiceImplementation.cs
> +            GC.SuppressFinalize(this);
Здесь нет неуправляемых ресурсов, финазатор гасить не нужно

void Dispose(bool disposing) - тоже не нужен

2024-07-31 13:56 UTC, Mblkolo commented on src/Abstractions/Validation/ServiceValidator.cs
> +            var dependenciesByValidators = _dependencyValidators.Values.ToDictionary(x => x, _ => new List<DependencyBase>());
Разве там можно? в ключе наследник IDependencyValidator и у него нет компарера. Словарь будет работать по сравнению ссылки объекта. Как-то не круто. 
Могут ли валидаторы повторяться для разных типов?

2024-07-31 13:56 UTC, Mblkolo commented on README.md
> +## Usage
Нужно обсудить на уровне концепции. Мне кажется, что компарить клиент не должен. Он должен сделать поставщик зависимостей, а сравнить и ругнуться должна инфра.
Просто вот у меня есть пакет с архитектурой, я его подключил... и как мне понять, что я не соответствую архитектуре?
Я думал, меня будут мучать, пока я её не удовлетворю.

2024-08-05 04:56 UTC, Rinatich requested changes

2024-08-05 04:56 UTC, Rinatich commented on src/Abstractions/Validation/Extensions/AssemblyExtensions.cs
> +        public static bool IsAssemblyNameEquals(this Assembly assembly, string assemblyName)
не по-английски ) может, лучше AssemblyNameEquals без Is. Если по-английски, то DoesAssemblyNameEqual

2024-08-05 04:56 UTC, Rinatich commented on src/Abstractions/Validation/Extensions/AssemblyNameExtensions.cs
> +        public static bool IsFullNameStartWith(this AssemblyName assemblyName, params string[] patterns)
не по-английски ) может, лучше FullNameStartsWith без Is. Если по-английски, то DoesFullNameStartWith

2024-08-05 04:56 UTC, Rinatich commented on src/Abstractions/Validation/Extensions/EnumExtensions.cs
> +                throw new InvalidOperationException($"{nameof(DescriptionAttribute)} was not declared for {nameof(member)}");
Обычно, если нет атрибута, лучше вернуть значение Enum. Падать не стоит, имхо )

2024-08-05 04:56 UTC, Rinatich commented on src/Abstractions/Validation/ServiceValidator.cs
> +            var dependenciesByValidators = _dependencyValidators.Values.ToDictionary(x => x, _ => new List<DependencyBase>());
Согласен, я бы тоже лучше создал словарь _dependenciesByDependencyType, а в конце доставал бы валидатор по типу ) так опасно

2024-08-05 04:56 UTC, Rinatich commented on src/Abstractions/Validation/ServiceValidatorExtensions.cs
> +    public static class ServiceValidatorExtensions
Это не экстеншн ) почему бы не вынести этот метод в ServiceValidatorBuilder?

2024-08-05 04:56 UTC, Rinatich commented on src/StructurizrParser/Model/ElementExtensions.cs
> +        public static bool IsWebApi(this Element element) => element.HasTag("WebApi");
Константы напрашиваются )

2024-08-07 07:19 UTC, litichevskiydv commented on src/Abstractions/Validation/ServiceValidator.cs
> +            var dependenciesByValidators = _dependencyValidators.Values.ToDictionary(x => x, _ => new List<DependencyBase>());
Переделал кусок, попутно добавил `ServiceValidationConfiguration` для возможности игнорирования определенных типов зависимостей

2024-08-07 07:44 UTC, litichevskiydv commented on examples/Api.Tests/musicality-labs.dsl
> +		container storage {
Да, поудалял табы.

2024-08-07 09:21 UTC, litichevskiydv commented on src/Abstractions/ServiceImplementations/ServiceImplementation.cs
> +            GC.SuppressFinalize(this);
Сделано

2024-08-07 09:27 UTC, litichevskiydv commented on src/Abstractions/Validation/Extensions/AssemblyNameExtensions.cs
> +        public static bool IsFullNameStartWith(this AssemblyName assemblyName, params string[] patterns)
Переименовал

2024-08-07 09:27 UTC, litichevskiydv commented on src/Abstractions/Validation/Extensions/AssemblyExtensions.cs
> +        public static bool IsAssemblyNameEquals(this Assembly assembly, string assemblyName)
Переименовал

2024-08-07 09:42 UTC, litichevskiydv commented on src/Abstractions/Validation/Extensions/EnumExtensions.cs
> +                throw new InvalidOperationException($"{nameof(DescriptionAttribute)} was not declared for {nameof(member)}");
Переделал

2024-08-07 10:08 UTC, litichevskiydv commented on src/Abstractions/Validation/ServiceValidatorExtensions.cs
> +    public static class ServiceValidatorExtensions
Переделал в фабрику

2024-08-07 10:19 UTC, litichevskiydv commented on src/StructurizrParser/Model/ElementExtensions.cs
> +        public static bool IsWebApi(this Element element) => element.HasTag("WebApi");
Предлагаю не вводить их здесь, поскольку значения не переиспользуются и вполне говорящие, какую задачу мы хотив решить их добалением?

2024-08-07 10:39 UTC, litichevskiydv commented on README.md
> +- add the architecture package and the `Byndyusoft.ArchitectureTesting.StructurizrParser` package to the project;
Добавил описание

2024-08-07 11:17 UTC, litichevskiydv commented on README.md
> +## Usage
Добавил описание концепции

2024-08-13 07:33 UTC, Rinatich approved these changes

2024-08-15 07:44 UTC, Mblkolo approved these changes

2024-08-20 08:21 UTC, merged